### ISSUE TITLE
Powershell Write-Output support

### ISSUE THREAD

**Issue by claytonaalves** [kragniz/anyprint#14]
It would be really useful to add windows powershell syntax support for "Write-Output" cmdlet.

Here is an example:

`Write-Output This is a test`

output:

```
This
is
a
test
```

:stuck_out_tongue_winking_eye:

**Comment by kragniz** [comment]
Sadly this isn't valid python syntax, so can't easily be added. If you find a way to make python parse it, please file a pull request!
