### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by davy-tw** [kragniz/anyprint#17]
[Ruby](https://www.ruby-lang.org/) is a popular language, it's on top 20 of [TOBIE Index](https://www.tiobe.com/tiobe-index/) and even get top 1 at 2006.

So anyprint should support least one of Ruby's print methods: 

```
puts "Ruby"
print "💎"
p "❤"
```

**Comment by SylvainDe** [comment]
This may be handled by https://github.com/kragniz/anyprint/pull/12 .

**Comment by alenthomas** [comment]
@SylvainDe 
in this #12 for the above to work doesn't it need to be 
`p("❤")` rather than `p "❤"` ?

**Comment by SylvainDe** [comment]
@alenthomas I didn't read the issue properly at first and did not notice the parentheses thing. In any case, I do not see any way to make this work as this does not fit in the already existing Python syntax...

**Comment by kragniz** [comment]
Yeah, this isn't valid python syntax, so can't easily be added. If you find a way to make python parse it, please file a pull request!
