### ISSUE TITLE
Add support for prefixed `std::` in C++

### ISSUE THREAD

**Issue by erip** [kragniz/anyprint#20]
As well all know, if you write `using namespace std;`, you're a plebe. 

Please add support for idiomatic C++ in Python.

```
std::cout << "Hello, C++ pedant!\n";
```

**Comment by bl4ckb0ne** [comment]
And the support of [std::printf](http://en.cppreference.com/w/cpp/io/c/fprintf) because std::cout is for the plebs.

**Comment by erip** [comment]
Please don't listen to this person. @Bl4ckb0ne is a heretic.

😅

**Comment by HarkonenBade** [comment]
I think this may hit the #3 issue.

**Comment by erip** [comment]
Not sure how. Adding `std::` to the already-enumerated C++ print doesn't change the grammar.

**Comment by HarkonenBade** [comment]
It's more that `::` is not a valid part of an identifier in python, and is not any other sort of valid syntactic construct. So you couldn't have `std::cout` be the name of an object, either directly or indirectly.
